spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/online_exam?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: false
mybatis:
  # 导入SQL语句配置文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
